name: ROS 2 CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-colcon-common-extensions
          sudo apt install -y python3-colcon-lint

      - name: Lint
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon lint --packages-select

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-colcon-common-extensions

      - name: Build
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon build --symlink-install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: jazzy

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y python3-colcon-common-extensions

      - name: Test
        run: |
          source /opt/ros/jazzy/setup.bash
          colcon test --packages-select --event-handlers console_cohesion+
